
package projecteuler;

/**
 *
 * @author rewil
 */
public class Problem2 implements Problem{

    String prompt = "Problem 2: \n" + 
                    "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:\n" +
                    "1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n" +
                    "By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.";
    
    public void solve() {
        int cap = 4000000;
        int sum = 0;
        
        Fibonacci f = new Fibonacci();
        while(f.next() <= cap) {
            if(f.getCurrent() % 2 == 0) sum += f.getCurrent();
        }
        
        System.out.println(prompt + '\n');
        System.out.println("Total: " + sum);
    }
    
    private class Fibonacci{
        int previous = 0;
        int current = 1;
        
        int index = 1;
        public int next() {
            int temp = previous;
            previous = current;
            current += temp;
            index ++;
            return current;
        }
        
        public int getCurrent() {
            return current;
        }
        public int getIndex() {
            return index;
        }
        
    }
    
}
